services:
  gis_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - POSTGRESQL_CONNECTION_STRING=Host=gis_database;Port=5432;Database=gis_data;Username=api_service;Password=db123
    ports:
      - "8080:8080"
    networks:
      - gis_db_connection
    restart: unless-stopped

  gis_database:
    image: postgis/postgis:17-master
    container_name: gis_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gis_data
      - POSTGRES_USER=api_service
      - POSTGRES_PASSWORD=db123
    volumes:
      - gis_data:/var/lib/postgresql/data
    networks:
      - gis_db_connection
    restart: unless-stopped    

  gis_client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://localhost:8080/api/v1
    container_name: gis_client
    environment:
      - VITE_BASE_URL=http://gis_api:8080/api/v1
    ports:
      - "80:80"
    networks:
      - gis_db_connection
    restart: unless-stopped

networks:
  gis_db_connection:
    driver: bridge

volumes:
  gis_data: